name: ros-deb-pkg

on:
  workflow_dispatch:
  push:
    branches:
      - test-ros-deb-pkg

jobs:
  ros-deb-pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          ROS_DISTRO: humble
          DEB_DISTRO: jammy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
